"""initial

Revision ID: fbf56e7f1a17
Revises: None
Create Date: 2026-05-30 20:03:50.275287
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fbf56e7f1a17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('blob_path', sa.String(length=500), nullable=False),
    sa.Column('blob_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('first_accessed_at', sa.DateTime(), nullable=True),
    sa.Column('burn_after_read', sa.Boolean(), nullable=True),
    sa.Column('burned', sa.Boolean(), nullable=True),
    sa.Column('has_access_password', sa.Boolean(), nullable=True),
    sa.Column('access_verifier', sa.LargeBinary(), nullable=True),
    sa.Column('access_verifier_salt', sa.LargeBinary(), nullable=True),
    sa.Column('access_verifier_iv', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_metadata', sa.LargeBinary(), nullable=True),
    sa.Column('encryption_iv', sa.LargeBinary(), nullable=True),
    sa.Column('delete_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('blob_path')
    )
    op.create_table('upload_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('total_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('chunk_size_bytes', sa.Integer(), nullable=False),
    sa.Column('received_chunks_json', sa.Text(), nullable=False),
    sa.Column('scratch_prefix', sa.String(length=500), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_sessions')
    op.drop_table('files')
    # ### end Alembic commands ###
